# Generated by Django 4.1.7 on 2023-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date_of_publish', models.DateField()),
                ('up_vote', models.IntegerField()),
                ('is_proven', models.BooleanField()),
                ('before_edit_content', models.TextField()),
                ('after_edit_content', models.TextField()),
                ('date_of_editing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('place_of_death', models.CharField(max_length=30)),
                ('blame', models.TextField()),
                ('rehabilitated', models.BooleanField()),
                ('occupation', models.CharField(max_length=30)),
                ('bedfellow', models.CharField(max_length=30)),
                ('children', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
