# Generated by Django 4.1.7 on 2023-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Victim',
        ),
    ]
