# Generated by Django 4.1.7 on 2023-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_person_victim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='after_edit_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='before_edit_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_editing',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_proven',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_vote',
            field=models.IntegerField(blank=True),
        ),
    ]
