# Generated by Django 4.1.7 on 2023-05-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0002_alter_victim_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='after_edit_content',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='before_edit_content',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='date_of_editing',
        ),
        migrations.AlterField(
            model_name='victim',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EditingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_editing', models.DateTimeField(default=django.utils.timezone.now)),
                ('letters_edited', models.IntegerField()),
                ('before_edit_content', models.TextField()),
                ('after_edit_content', models.TextField()),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.victim')),
            ],
        ),
    ]
