# Generated by Django 4.1.7 on 2023-05-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_victim_after_edit_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editinghistory',
            name='letters_edited',
        ),
    ]
