# Generated by Django 4.1.7 on 2023-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_editing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_vote',
            field=models.IntegerField(),
        ),
    ]
