# Generated by Django 4.1.7 on 2023-04-03 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_article_date_of_editing_alter_article_up_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='after_edit_content',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='before_edit_content',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_editing',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_publish',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_proven',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
