# Generated by Django 4.1.7 on 2023-04-04 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_article_title_alter_article_after_edit_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='victim',
            name='after_edit_content',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='victim',
            name='before_edit_content',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='victim',
            name='content',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='victim',
            name='date_of_editing',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='victim',
            name='date_of_publish',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='victim',
            name='is_proven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='victim',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
