# Generated by Django 4.1.7 on 2023-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_delete_article_victim_after_edit_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
