# Generated by Django 4.1.7 on 2023-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_victim_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
