# Generated by Django 4.1.7 on 2023-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_victim_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='nationality',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='victim',
            name='rehabilitated',
            field=models.CharField(max_length=30),
        ),
    ]
