# Generated by Django 4.1.7 on 2023-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_victim_nationality_alter_victim_rehabilitated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
