# Generated by Django 4.1.7 on 2023-05-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_victim_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='desc_of_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='desc_of_photo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='after_edit_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='victim',
            name='bedfellow',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='before_edit_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='victim',
            name='blame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='children',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='nationality',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='rehabilitated',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
